### ISSUE TITLE
Error generating diffmeth reports 

### ISSUE THREAD

**Issue by srikanthkris** [BIMSBbioinfo/pigx_bsseq#158]
Hi, 

 i am getting some error while generating diffmeth report.

it is due to non-standard chromosomal names in the bed file i think.

But not really sure which script file must be edited to tide over this. 

The issue seems to be in ggbio/granges package.
Attaching the log file below 

Can you please help.

[diffmeth-report.0vs1.log](https://github.com/BIMSBbioinfo/pigx_bsseq/files/4721185/diffmeth-report.0vs1.log)

**Comment by alexg9010** [comment]
Hi @srikanthkris ,

Probably your error is due to this line: https://github.com/BIMSBbioinfo/pigx_bsseq/blob/master/report_templates/diffmeth.Rmd.in#L353 . It seems that some of your reads mapped to non-standard chromosomes. 

When creating the ideoDMC plot we are subsetting to only these standard chromosomes, see here https://github.com/BIMSBbioinfo/pigx_bsseq/blob/master/scripts/ideoDMC.R#L119-L123 .  

So depending on whether you trust the mapping to non-standard chroms you could try to remove https://github.com/BIMSBbioinfo/pigx_bsseq/blob/master/report_templates/diffmeth.Rmd.in#L353. 

Or what I would suggest is to subset to all only standard chromosomes (https://github.com/BIMSBbioinfo/pigx_bsseq/blob/master/scripts/ideoDMC.R#L119-L123):
```
seqlevels(g.per, pruning.mode="coarse") = seqlevels(myIdeo)
[...]
seqlevels(g.po, pruning.mode="coarse") = seqlevels(myIdeo)
```

Hope this helps for now.
I will be adding a fix for this as soon as possible, but if you installed the pipeline from github please feel free to fix it yourself and submit a pull request once it works. 

Best,
Alex

**Comment by srikanthkris** [comment]
Thanks alex for a super fast response. 
You are fantastic.
That fixed it. I will try to make a pull request.
