### ISSUE TITLE
snakemake requires extra space  

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/pigx_bsseq#33]
when you call `./bin/pigx_bs -s "-n" test/Tablesheet.txt` the call will fail, since the argument for -s is not properly recognized as one argument. 

maybe @rekado has a solution to circumvent this behavior

**Comment by rekado** [comment]
alexg9010 writes:

> when you call ./bin/pigx_bs -s "-n" test/Tablesheet.txt the call will
> fail, since the argument for -s is not properly recognized as one
> argument.

This happens because “"-n"” is the same as just -n and thus is
recognized as an option to pigx_bs, not as an argument to “-s”.  I
believe that the quotes are stripped off by the shell already, so
pigx_bs never gets to see the quotes in the case of “"-n"”.

Only when the space is included the shell passes the string “ -n”, which
does not begin with “-” and thus is not processed by Python’s argparse
library.

A convention in many command line applications is to use “--” as a
separator of options, where everything after “--” is passed to the
spawned process (cf “ssh” or “guix environment”).  We could demand that
users provide snakemake arguments after “--”; then we could tell
argparse to greedily slurp up all text after “--” and barf it to
snakemake.  This requires that “--” be the last option, though.

An alternative is to make this less flexible and add common snakemake
options to pigx_bs itself, e.g. “--dry-run”, which is then explicitly
passed to snakemake.

--
Ricardo

GPG: BCA6 89B6 3655 3801 C3C6  2150 197A 5888 235F ACAC
https://elephly.net

**Comment by rekado** [comment]
I think we might be able to fix this by telling argparse that `-s` requires exactly one argument.  I'm trying this now.

**Comment by rekado** [comment]
That didn't work.  Users either need to use the long version with an equal sign between flag and value, or they need a space.  `argparse` cannot easily deal with argument values starting with a dash.

**Comment by rekado** [comment]
As discussed, we'll hoist selected snakemake flags up to pigx-bsseq instead of offering a generic way to edit the snakemake command line.  These flags will be "--dry-run/-n", "--dag", and "--force".
